# Generated by Django 4.2.20 on 2025-05-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arc_type', models.CharField(choices=[('similarity', 'Similarity'), ('contrast', 'Contrast'), ('cause_effect', 'Cause and Effect'), ('example', 'Example'), ('elaboration', 'Elaboration'), ('sequence', 'Sequence'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('strength', models.IntegerField(default=5, help_text='Strength of connection (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('raw_content', models.TextField(help_text='The original, unprocessed text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('character_count', models.PositiveIntegerField()),
                ('is_illuminated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.cognition')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('cognition', 'position')},
            },
        ),
        migrations.CreateModel(
            name='PresetResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='synthesis', to='api.node')),
            ],
        ),
        migrations.CreateModel(
            name='SynthesisPresetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preset_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.presetresponse')),
                ('synthesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_links', to='api.synthesis')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('synthesis', 'preset_response')},
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='synthesis',
            name='preset_responses',
            field=models.ManyToManyField(blank=True, through='api.SynthesisPresetLink', to='api.presetresponse'),
        ),
        migrations.AddField(
            model_name='arc',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_arcs', to='api.node'),
        ),
        migrations.AddField(
            model_name='arc',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_arcs', to='api.node'),
        ),
        migrations.AlterUniqueTogether(
            name='arc',
            unique_together={('source_node', 'target_node', 'arc_type')},
        ),
    ]
