# Generated by Django 4.2.20 on 2025-05-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_arc_cognition_node_presetresponse_synthesis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognition',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='Indicates if this cognition is starred for quick access'),
        ),
    ]
