# Generated by Django 4.2.20 on 2025-05-17 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_cognition_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognition',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this cognition is shared publicly'),
        ),
        migrations.AddField(
            model_name='cognition',
            name='share_date',
            field=models.DateTimeField(blank=True, help_text='When this cognition was shared', null=True),
        ),
        migrations.AddField(
            model_name='cognition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cognitions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='api.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
