version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app
      - backend_static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key_change_in_production
      - DJANGO_SETTINGS_MODULE=backend.settings
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    restart: unless-stopped

volumes:
  backend_static: