

// Social action types
export const FETCH_COLLECTIVE_REQUEST = 'FETCH_COLLECTIVE_REQUEST';
export const FETCH_COLLECTIVE_SUCCESS = 'FETCH_COLLECTIVE_SUCCESS';
export const FETCH_COLLECTIVE_FAILURE = 'FETCH_COLLECTIVE_FAILURE';

export const TOGGLE_SHARE_REQUEST = 'TOGGLE_SHARE_REQUEST';
export const TOGGLE_SHARE_SUCCESS = 'TOGGLE_SHARE_SUCCESS';
export const TOGGLE_SHARE_FAILURE = 'TOGGLE_SHARE_FAILURE';

export const FETCH_PROFILES_REQUEST = 'FETCH_PROFILES_REQUEST';
export const FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS';
export const FETCH_PROFILES_FAILURE = 'FETCH_PROFILES_FAILURE';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE';